src/plates.c File Reference
#include `plates.h`
*
Functions
static bool is_valid_plate (char *plate)
static bool are_old_plate_chars (char *plate)
static bool is_old_plate (char *plate)
static bool is_new_plate_alpha (char a)
static bool are_new_plate_chars (char *plate)
static bool is_new_plate (char *plate)
plate_t check_plate (char *plate)
Variables
static const char U = 'U'
static const char Q = 'Q'
static const char O = 'O'
static const char I = 'I'
static const char G = 'G'
static const int EIGHT = 8
static const int SEVEN = 7
static const int FOUR = 4
static const int THREE = 3
static const int TWO = 2
static const int ONE = 1
static const int ZERO = 0
Function Documentation
static bool are_new_plate_chars (char * plate) [static]
Definition at line 46 of file plates.c.
References FOUR, is_new_plate_alpha(), THREE, TWO, and ZERO.
Referenced by is_new_plate().
static bool are_old_plate_chars (char * plate) [static]
Definition at line 30 of file plates.c.
References ONE, TWO, and ZERO.
Referenced by is_old_plate().
plate_t check_plate (char * plate)
Restituisce il tipo di targa. La funzione riconosce due soli tipi di targa: vecchio tipo o nuovo tipo. Per targhe di vecchio tipo, il metodo restituisce OLD_PLATE; per targhe di nuovo tipo il metodo restituisce NEW_PLATE. Se la funzione non riconosce il tipo di targa, restituisce UNRECOGNIZED.
TARGHE DI VECCHIO TIPO
 Una targa di vecchio tipo e' costituita da 8 caratteri. I primi due caratteri sono lettere, gli ultimi cinque caratteri sono cifre. Il terzo carattere puo' essere lettera o cifra.
TARGHE DI NUOVO TIPO
 Una targa di nuovo tipo e' costituita da 7 caratteri. I primi due caratteri e gli ultimi due caratteri sono lettere AMMESSE. I tre caratteri centrali sono cifre. Le lettere ammesse sono tutte le lettere dell'alfabeto TRANNE: GIOQU
Precondition
plate non puo' essere null e deve essere costituita esclusivamente da caratteri alfanumerici.
Postcondition
il valore restituito puo' essere solo OLD_PLATE, NEW_PLATE oppure UNRECOGNIZED.
Parameters
in plate la targa automobilistica
Returns
il tipo di targa
Definition at line 58 of file plates.c.
References is_new_plate(), is_old_plate(), is_valid_plate(), NEW_PLATE, OLD_PLATE, and UNRECOGNIZED.
static bool is_new_plate (char * plate) [static]
Definition at line 54 of file plates.c.
References are_new_plate_chars(), and SEVEN.
Referenced by check_plate().
static bool is_new_plate_alpha (char a) [static]
Definition at line 42 of file plates.c.
References G, I, O, Q, and U.
Referenced by are_new_plate_chars().
static bool is_old_plate (char * plate) [static]
Definition at line 38 of file plates.c.
References are_old_plate_chars(), and EIGHT.
Referenced by check_plate().
static bool is_valid_plate (char * plate) [static]
Definition at line 23 of file plates.c.
References ZERO.
Referenced by check_plate().
Variable Documentation
const int EIGHT = 8 [static]
Definition at line 15 of file plates.c.
Referenced by is_old_plate().
const int FOUR = 4 [static]
Definition at line 17 of file plates.c.
Referenced by are_new_plate_chars().
const char G = 'G' [static]
Definition at line 14 of file plates.c.
Referenced by is_new_plate_alpha().
const char I = 'I' [static]
Definition at line 13 of file plates.c.
Referenced by is_new_plate_alpha().
const char O = 'O' [static]
Definition at line 12 of file plates.c.
Referenced by is_new_plate_alpha().
const int ONE = 1 [static]
Definition at line 20 of file plates.c.
Referenced by are_old_plate_chars().
const char Q = 'Q' [static]
Definition at line 11 of file plates.c.
Referenced by is_new_plate_alpha().
const int SEVEN = 7 [static]
Definition at line 16 of file plates.c.
Referenced by is_new_plate().
const int THREE = 3 [static]
Definition at line 18 of file plates.c.
Referenced by are_new_plate_chars().
const int TWO = 2 [static]
Definition at line 19 of file plates.c.
Referenced by are_new_plate_chars(), and are_old_plate_chars().
const char U = 'U' [static]
Definition at line 10 of file plates.c.
Referenced by is_new_plate_alpha().
const int ZERO = 0 [static]
Definition at line 21 of file plates.c.
Referenced by are_new_plate_chars(), are_old_plate_chars(), and is_valid_plate().